In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

# Optional (just makes tables look nicer in notebook)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

# Load 2025 play-by-play data
df = nfl.import_pbp_data([2025])

# Quick sanity check
print("Shape:", df.shape)
df.head()

2025 done.
Downcasting floats.
Shape: (48771, 397)

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,nflverse_game_id,old_game_id_y,possession_team,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
0,1.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,None,None,None,None,NaN,2025-09-07,900.0,1800.0,3600.0,Half1,0.0,NaN,0.0,1.0,NaN,0,15:00,NO 35,0.0,NaN,GAME,None,NaN,0.0,0.0,NaN,0.0,0.0,0.0,None,None,NaN,NaN,None,None,None,NaN,None,None,3.0,3.0,NaN,None,None,None,None,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.008251,-0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.433208,0.566792,0.566792,0.433208,-0.000000,-0.000000,0.000000,NaN,NaN,0.725613,0.274387,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,0.0,None,None,NaN,NaN,NaN,NaN,None,None,2025,NaN,NaN,1.0,1.0,First down,1.0,"9/7/25, 13:02:38",None,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,GAME_START,0.0,None,None,None,1.0,Punt,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,None,NaN,None,NaN,None,NaN,0.0,0.0,NaN,0.0,0.0,None,None,None,None,NaN,None,None,None,None,None,0.0,0.0,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,NO,35.0,2025-09-07,900.0,1800.0,3600.0,Half1,0.0,1.0,0.0,1.0,NaN,0,15:00,NO 35,0.0,2.0,19-B.Grupe kicks 65 yards from NO 35 to ARI 0....,kickoff,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,None,65.0,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003473,0.128879,0.002270,0.272088,0.208195,0.003240,0.381854,0.0,0.0,1.008251,-0.352700,0.352700,-0.352700,0.000000,0.000000,0.00000,0.00000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.433208,0.566792,0.566792,0.433208,0.000701,-0.009752,0.009752,0.566091,0.433909,0.725613,0.274387,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,G.Dortch,00-0035500,None,None,None,None,B.Grupe,00-0038905,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0040155,None,D.Stutsman,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,ARI,22.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,1.0,1.0,First down,40.0,"9/7/25, 13:02:38",2025-09-07T17:02:38.787Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,KICK_OFF,1.0,None,2025-09-07T17:02:46.793Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,None,NaN,None,NaN,None,NaN,0.0,0.0,0.0,1.0,0.0,None,None,None,None,NaN,None,None,None,None,None,0.0,0.0,-0.352700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025_01_ARI_NO,2025090705,ARI,None,"1 CB, 2 FS, 2 ILB, 1 RB, 1 S, 3 TE, 1 WR",0.0,"2 CB, 2 FS, 2 ILB, 1 K, 1 MLB, 1 OLB, 1 RB, 1 SS",0.0,00-0038781;00-0040166;00-0040195;00-0035142;00...,00-0040195;00-0037141;00-0039864;00-0038600;00...,00-0038781;00-0040166;00-0035142;00-0036253;00...,11.0,11.0,NaN,NaN,False,,,None,Denzel Burke;Joey Blount;Dadrion Taylor-Demers...,Rejzohn Wright;Quincy Riley;Ugo Amadi;Julian B...,CB;FS;FS;ILB;ILB;RB;S;TE;TE;TE;WR,CB;CB;FS;FS;ILB;ILB;K;MLB;OLB;RB;SS,29;32;42;44;50;31;36;84;81;87;4,25;29;0;23;53;44;19;28;40;13;33
2,63.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,78.0,2025-09-07,896.0,1796.0,3596.0,Half1,0.0,1.0,0.0,1.0,1.0,0,14:56,ARI 22,10.0,2.0,(14:56) 6-J.Conner right tackle to ARI 25 for ...,run,3.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,right,tackle,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003538,0.147130,0.002386,0.288428,0.192967,0.003409,0.362142,0.0,0.0,0.655552,-0.190052,0.542752,-0.542752,0.190052,-0.190052,0.00000,0.00000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.433909,0.566091,0.566091,0.433909,-0.014005,-0.012243,0.012243,0.580096,0.419904,0.715861,0.284139,0.014005,-0.014005,0.000000,0.000000,NaN,NaN,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0033553,J.Conner,3.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0033860,None,D.Godchaux,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,1.0,1.0,First down,63.0,"9/7/25, 13:02:38",2025-09-07T17:03:24.483Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T17:03:27.673Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,None,NaN,J.Conner,6.0,None,NaN,0.0,1.0,0.0,0.0,1.0,None,00-0033553,None,J.Conner,6.0,00-0033553,J.Conner,00-0033553,J.Conner,00-0033553,0.0,0.0,-0.190052,NaN,NaN,NaN,NaN,NaN,0.511128,-51.112808,2025_01_ARI_NO,2025090705,ARI,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 3 TE, 1 WR",6.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",0.0,00-0035258;00-0034780;00-0039860;00-0034760;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0039860;00-0034760;00-0038995;00...,11.0,11.0,NaN,NaN,False,,,None,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Kool-Aid McKinstry;Nathan Shepher...,C;G;G;QB;RB;T;T;TE;TE;TE;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,72;63;74;1;6;73;70;85;84;87;18,27;4;93;90;23;20;56;92;94;96;21
3,85.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,75.0,2025-09-07,858.0,1758.0,3558.0,Half1,0.0,1.0,0.0,1.0,2.0,0,14:18,ARI 25,7.0,2.0,(14:18) (Shotgun) 1-K.Murray pass short left t...,pass,11.0,1.0,0.0,1.0,0.0,0.0,0.0,short,left,3.0,8.0,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003934,0.146586,0.002361,0.300936,0.197541,0.003319,0.345324,0.0,0.0,0.465499,1.317340,-0.774588,0.774588,0.190052,-0.190052,-1.31734,1.31734,-0.359325,1.676665,-0.359325,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.419904,0.580096,0.580096,0.419904,0.034995,0.043085,-0.043085,0.545101,0.454899,0.703618,0.296382,0.014005,-0.014005,-0.034995,0.034995,0.0,0.034995,0.0,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0035228,K.Murray,11.0,00-0037744,T.McBride,11.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0034780,None,I.Yiadom,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,0.805343,19.46566,1.0,1.0,First down,85.0,"9/7/25, 13:02:38",2025-09-07T17:04:01.983Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,PASS,0.0,None,2025-09-07T17:04:06.587Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,1.0,K.Murray,1.0,None,NaN,T.McBride,85.0,1.0,0.0,1.0,0.0,1.0,00-0035228,None,00-0037744,K.Murray,1.0,00-0035228,T.McBride,00-0037744,T.McBride,00-0037744,1.0,0.0,1.317340,0.939998,4.750889,3.0,0.666726,0.43911,0.668940,33.105968,2025_01_ARI_NO,2025090705,ARI,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",7.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",4.0,00-0035258;00-0034780;00-0039860;00-0034760;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0039860;00-0034760;00-0038995;00...,11.0,11.0,NaN,1.3,False,QUICK OUT,ZONE_COVERAGE,COVER_2,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Kool-Aid McKinstry;Nathan Shepher...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,72;63;74;1;6;73;70;85;87;14;18,27;4;93;90;23;20;56;92;94;96;21

In [2]:
# =========================================================
# SECOND CELL — UNDERSTAND DATA STRUCTURE
# =========================================================

print("COLUMNS:\n")
print(df.columns.tolist())

print("\nPLAY TYPE COUNTS:\n")
print(df['play_type'].value_counts(dropna=False))

print("\nDOWN VALUES:\n")
print(df['down'].value_counts(dropna=False))

print("\nPOSTEAM VALUES (first 20):\n")
print(df['posteam'].dropna().unique()[:20])

COLUMNS:

['play_id', 'game_id', 'old_game_id_x', 'home_team', 'away_team', 'season_type', 'week', 'posteam', 'posteam_type', 'defteam', 'side_of_field', 'yardline_100', 'game_date', 'quarter_seconds_remaining', 'half_seconds_remaining', 'game_seconds_remaining', 'game_half', 'quarter_end', 'drive', 'sp', 'qtr', 'down', 'goal_to_go', 'time', 'yrdln', 'ydstogo', 'ydsnet', 'desc', 'play_type', 'yards_gained', 'shotgun', 'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble', 'pass_length', 'pass_location', 'air_yards', 'yards_after_catch', 'run_location', 'run_gap', 'field_goal_result', 'kick_distance', 'extra_point_result', 'two_point_conv_result', 'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout', 'timeout_team', 'td_team', 'td_player_name', 'td_player_id', 'posteam_timeouts_remaining', 'defteam_timeouts_remaining', 'total_home_score', 'total_away_score', 'posteam_score', 'defteam_score', 'score_differential', 'posteam_score_post', 'defteam_score_post', 'score_differential_post', 'no_score_prob', 'opp_fg_prob', 'opp_safety_prob', 'opp_td_prob', 'fg_prob', 'safety_prob', 'td_prob', 'extra_point_prob', 'two_point_conversion_prob', 'ep', 'epa', 'total_home_epa', 'total_away_epa', 'total_home_rush_epa', 'total_away_rush_epa', 'total_home_pass_epa', 'total_away_pass_epa', 'air_epa', 'yac_epa', 'comp_air_epa', 'comp_yac_epa', 'total_home_comp_air_epa', 'total_away_comp_air_epa', 'total_home_comp_yac_epa', 'total_away_comp_yac_epa', 'total_home_raw_air_epa', 'total_away_raw_air_epa', 'total_home_raw_yac_epa', 'total_away_raw_yac_epa', 'wp', 'def_wp', 'home_wp', 'away_wp', 'wpa', 'vegas_wpa', 'vegas_home_wpa', 'home_wp_post', 'away_wp_post', 'vegas_wp', 'vegas_home_wp', 'total_home_rush_wpa', 'total_away_rush_wpa', 'total_home_pass_wpa', 'total_away_pass_wpa', 'air_wpa', 'yac_wpa', 'comp_air_wpa', 'comp_yac_wpa', 'total_home_comp_air_wpa', 'total_away_comp_air_wpa', 'total_home_comp_yac_wpa', 'total_away_comp_yac_wpa', 'total_home_raw_air_wpa', 'total_away_raw_air_wpa', 'total_home_raw_yac_wpa', 'total_away_raw_yac_wpa', 'punt_blocked', 'first_down_rush', 'first_down_pass', 'first_down_penalty', 'third_down_converted', 'third_down_failed', 'fourth_down_converted', 'fourth_down_failed', 'incomplete_pass', 'touchback', 'interception', 'punt_inside_twenty', 'punt_in_endzone', 'punt_out_of_bounds', 'punt_downed', 'punt_fair_catch', 'kickoff_inside_twenty', 'kickoff_in_endzone', 'kickoff_out_of_bounds', 'kickoff_downed', 'kickoff_fair_catch', 'fumble_forced', 'fumble_not_forced', 'fumble_out_of_bounds', 'solo_tackle', 'safety', 'penalty', 'tackled_for_loss', 'fumble_lost', 'own_kickoff_recovery', 'own_kickoff_recovery_td', 'qb_hit', 'rush_attempt', 'pass_attempt', 'sack', 'touchdown', 'pass_touchdown', 'rush_touchdown', 'return_touchdown', 'extra_point_attempt', 'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt', 'punt_attempt', 'fumble', 'complete_pass', 'assist_tackle', 'lateral_reception', 'lateral_rush', 'lateral_return', 'lateral_recovery', 'passer_player_id', 'passer_player_name', 'passing_yards', 'receiver_player_id', 'receiver_player_name', 'receiving_yards', 'rusher_player_id', 'rusher_player_name', 'rushing_yards', 'lateral_receiver_player_id', 'lateral_receiver_player_name', 'lateral_receiving_yards', 'lateral_rusher_player_id', 'lateral_rusher_player_name', 'lateral_rushing_yards', 'lateral_sack_player_id', 'lateral_sack_player_name', 'interception_player_id', 'interception_player_name', 'lateral_interception_player_id', 'lateral_interception_player_name', 'punt_returner_player_id', 'punt_returner_player_name', 'lateral_punt_returner_player_id', 'lateral_punt_returner_player_name', 'kickoff_returner_player_name', 'kickoff_returner_player_id', 'lateral_kickoff_returner_player_id', 'lateral_kickoff_returner_player_name', 'punter_player_id', 'punter_player_name', 'kicker_player_name', 'kicker_player_id', 'own_kickoff_recovery_player_id', 'own_kickoff_recovery_player_name', 'blocked_player_id', 'blocked_player_name', 'tackle_for_loss_1_player_id', 'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id', 'tackle_for_loss_2_player_name', 'qb_hit_1_player_id', 'qb_hit_1_player_name', 'qb_hit_2_player_id', 'qb_hit_2_player_name', 'forced_fumble_player_1_team', 'forced_fumble_player_1_player_id', 'forced_fumble_player_1_player_name', 'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id', 'forced_fumble_player_2_player_name', 'solo_tackle_1_team', 'solo_tackle_2_team', 'solo_tackle_1_player_id', 'solo_tackle_2_player_id', 'solo_tackle_1_player_name', 'solo_tackle_2_player_name', 'assist_tackle_1_player_id', 'assist_tackle_1_player_name', 'assist_tackle_1_team', 'assist_tackle_2_player_id', 'assist_tackle_2_player_name', 'assist_tackle_2_team', 'assist_tackle_3_player_id', 'assist_tackle_3_player_name', 'assist_tackle_3_team', 'assist_tackle_4_player_id', 'assist_tackle_4_player_name', 'assist_tackle_4_team', 'tackle_with_assist', 'tackle_with_assist_1_player_id', 'tackle_with_assist_1_player_name', 'tackle_with_assist_1_team', 'tackle_with_assist_2_player_id', 'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team', 'pass_defense_1_player_id', 'pass_defense_1_player_name', 'pass_defense_2_player_id', 'pass_defense_2_player_name', 'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name', 'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team', 'fumble_recovery_1_team', 'fumble_recovery_1_yards', 'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name', 'fumble_recovery_2_team', 'fumble_recovery_2_yards', 'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name', 'sack_player_id', 'sack_player_name', 'half_sack_1_player_id', 'half_sack_1_player_name', 'half_sack_2_player_id', 'half_sack_2_player_name', 'return_team', 'return_yards', 'penalty_team', 'penalty_player_id', 'penalty_player_name', 'penalty_yards', 'replay_or_challenge', 'replay_or_challenge_result', 'penalty_type', 'defensive_two_point_attempt', 'defensive_two_point_conv', 'defensive_extra_point_attempt', 'defensive_extra_point_conv', 'safety_player_name', 'safety_player_id', 'season', 'cp', 'cpoe', 'series', 'series_success', 'series_result', 'order_sequence', 'start_time', 'time_of_day', 'stadium', 'weather', 'nfl_api_id', 'play_clock', 'play_deleted', 'play_type_nfl', 'special_teams_play', 'st_play_type', 'end_clock_time', 'end_yard_line', 'fixed_drive', 'fixed_drive_result', 'drive_real_start_time', 'drive_play_count', 'drive_time_of_possession', 'drive_first_downs', 'drive_inside20', 'drive_ended_with_score', 'drive_quarter_start', 'drive_quarter_end', 'drive_yards_penalized', 'drive_start_transition', 'drive_end_transition', 'drive_game_clock_start', 'drive_game_clock_end', 'drive_start_yard_line', 'drive_end_yard_line', 'drive_play_id_started', 'drive_play_id_ended', 'away_score', 'home_score', 'location', 'result', 'total', 'spread_line', 'total_line', 'div_game', 'roof', 'surface', 'temp', 'wind', 'home_coach', 'away_coach', 'stadium_id', 'game_stadium', 'aborted_play', 'success', 'passer', 'passer_jersey_number', 'rusher', 'rusher_jersey_number', 'receiver', 'receiver_jersey_number', 'pass', 'rush', 'first_down', 'special', 'play', 'passer_id', 'rusher_id', 'receiver_id', 'name', 'jersey_number', 'id', 'fantasy_player_name', 'fantasy_player_id', 'fantasy', 'fantasy_id', 'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa', 'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd', 'xpass', 'pass_oe', 'nflverse_game_id', 'old_game_id_y', 'possession_team', 'offense_formation', 'offense_personnel', 'defenders_in_box', 'defense_personnel', 'number_of_pass_rushers', 'players_on_play', 'offense_players', 'defense_players', 'n_offense', 'n_defense', 'ngs_air_yards', 'time_to_throw', 'was_pressure', 'route', 'defense_man_zone_type', 'defense_coverage_type', 'offense_names', 'defense_names', 'offense_positions', 'defense_positions', 'offense_numbers', 'defense_numbers']

PLAY TYPE COUNTS:

play_type
pass           19735
run            14893
no_play         4732
kickoff         2918
punt            2042
None            1455
extra_point     1324
field_goal      1140
qb_kneel         452
qb_spike          80
Name: count, dtype: int64

DOWN VALUES:

down
1.0    16202
2.0    12352
NaN     7993
3.0     7934
4.0     4290
Name: count, dtype: int64

POSTEAM VALUES (first 20):

['ARI' 'NO' 'BUF' 'BAL' 'JAX' 'CAR' 'CIN' 'CLE' 'DAL' 'PHI' 'GB' 'DET'
 'HOU' 'LA' 'KC' 'LAC' 'LV' 'NE' 'IND' 'MIA']

In [3]:
# =========================================================
# THIRD CELL — CLEAN + FILTER DATA
# =========================================================

clean = df.copy()

# 1. Keep only run/pass plays
clean = clean[clean["play_type"].isin(["run", "pass"])]

# 2. Remove missing key values
clean = clean[
    clean["posteam"].notna() &
    clean["down"].notna() &
    clean["ydstogo"].notna() &
    clean["yards_gained"].notna() &
    clean["yardline_100"].notna()
]

# 3. Keep regular season only (important)
clean = clean[clean["season_type"] == "REG"]

# 4. Remove red zone (inside opponent 20)
clean = clean[clean["yardline_100"] > 20]

# 5. Remove backed up (own 1–10)
clean = clean[clean["yardline_100"] < 90]

# 6. Remove penalties / fake plays
clean = clean[clean["penalty"] != 1]

# 7. Remove spikes / kneels
clean = clean[clean["qb_spike"] != 1]
clean = clean[clean["qb_kneel"] != 1]

# 8. Keep only real downs
clean = clean[clean["down"].isin([1,2,3,4])]

# 9. Remove weird distances
clean = clean[clean["ydstogo"] > 0]

print("Clean shape:", clean.shape)
clean.head()

Clean shape: (26381, 397)

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,nflverse_game_id,old_game_id_y,possession_team,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
2,63.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,78.0,2025-09-07,896.0,1796.0,3596.0,Half1,0.0,1.0,0.0,1.0,1.0,0,14:56,ARI 22,10.0,2.0,(14:56) 6-J.Conner right tackle to ARI 25 for ...,run,3.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,right,tackle,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003538,0.147130,0.002386,0.288428,0.192967,0.003409,0.362142,0.0,0.0,0.655552,-0.190052,0.542752,-0.542752,0.190052,-0.190052,0.00000,0.00000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.433909,0.566091,0.566091,0.433909,-0.014005,-0.012243,0.012243,0.580096,0.419904,0.715861,0.284139,0.014005,-0.014005,0.000000,0.000000,NaN,NaN,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0033553,J.Conner,3.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0033860,None,D.Godchaux,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,1.0,1.0,First down,63.0,"9/7/25, 13:02:38",2025-09-07T17:03:24.483Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T17:03:27.673Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,None,NaN,J.Conner,6.0,None,NaN,0.0,1.0,0.0,0.0,1.0,None,00-0033553,None,J.Conner,6.0,00-0033553,J.Conner,00-0033553,J.Conner,00-0033553,0.0,0.0,-0.190052,NaN,NaN,NaN,NaN,NaN,0.511128,-51.112808,2025_01_ARI_NO,2025090705,ARI,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 3 TE, 1 WR",6.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",0.0,00-0035258;00-0034780;00-0039860;00-0034760;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0039860;00-0034760;00-0038995;00...,11.0,11.0,NaN,NaN,False,,,None,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Kool-Aid McKinstry;Nathan Shepher...,C;G;G;QB;RB;T;T;TE;TE;TE;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,72;63;74;1;6;73;70;85;84;87;18,27;4;93;90;23;20;56;92;94;96;21
3,85.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,75.0,2025-09-07,858.0,1758.0,3558.0,Half1,0.0,1.0,0.0,1.0,2.0,0,14:18,ARI 25,7.0,2.0,(14:18) (Shotgun) 1-K.Murray pass short left t...,pass,11.0,1.0,0.0,1.0,0.0,0.0,0.0,short,left,3.0,8.0,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003934,0.146586,0.002361,0.300936,0.197541,0.003319,0.345324,0.0,0.0,0.465499,1.317340,-0.774588,0.774588,0.190052,-0.190052,-1.31734,1.31734,-0.359325,1.676665,-0.359325,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.419904,0.580096,0.580096,0.419904,0.034995,0.043085,-0.043085,0.545101,0.454899,0.703618,0.296382,0.014005,-0.014005,-0.034995,0.034995,0.0,0.034995,0.0,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0035228,K.Murray,11.0,00-0037744,T.McBride,11.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0034780,None,I.Yiadom,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,0.805343,19.46566,1.0,1.0,First down,85.0,"9/7/25, 13:02:38",2025-09-07T17:04:01.983Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,PASS,0.0,None,2025-09-07T17:04:06.587Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,1.0,K.Murray,1.0,None,NaN,T.McBride,85.0,1.0,0.0,1.0,0.0,1.0,00-0035228,None,00-0037744,K.Murray,1.0,00-0035228,T.McBride,00-0037744,T.McBride,00-0037744,1.0,0.0,1.317340,0.939998,4.750889,3.0,0.666726,0.43911,0.668940,33.105968,2025_01_ARI_NO,2025090705,ARI,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",7.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",4.0,00-0035258;00-0034780;00-0039860;00-0034760;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0039860;00-0034760;00-0038995;00...,11.0,11.0,NaN,1.3,False,QUICK OUT,ZONE_COVERAGE,COVER_2,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Kool-Aid McKinstry;Nathan Shepher...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,72;63;74;1;6;73;70;85;87;14;18,27;4;93;90;23;20;56;92;94;96;21
4,115.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,64.0,2025-09-07,820.0,1720.0,3520.0,Half1,0.0,1.0,0.0,1.0,1.0,0,13:40,ARI 36,10.0,2.0,(13:40) 1-K.Murray sacked at ARI 25 for -11 ya...,pass,-11.0,0.0,0.0,1.0,0.0,0.0,0.0,None,None,NaN,NaN,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003802,0.107139,0.002015,0.223523,0.237726,0.004158,0.421637,0.0,0.0,1.782839,-1.694360,0.919772,-0.919772,0.190052,-0.190052,0.37702,-0.37702,NaN,NaN,0.000000,0.000000,0.359325,-0.359325,-1.676665,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.454899,0.545101,0.545101,0.454899,-0.050684,-0.087627,0.087627,0.595785,0.404215,0.746703,0.253297,0.014005,-0.014005,0.015689,-0.015689,NaN,NaN,0.0,0.000000,0.0,0.0,-0.034995,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0035228,K.Murray,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,00-0027962,C.Jordan,None,None,00-0027962,C.Jordan,None,None,None,None,None,None,None,None,NO,None,00-0027962,None,C.Jordan,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,00-0027962,C.Jordan,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,2.0,0.0,Punt,115.0,"9/7/25, 13:02:38",2025-09-07T17:04:42.290Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,SACK,0.0,None,2025-09-07T17:04:45.460Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,K.Murray,1.0,None,NaN,None,NaN,1.0,0.0,0.0,0.0,1.0,00-0035228,None,None,K.Murray,1.0,00-0035228,None,None,None,None,0.0,0.0,-1.694360,NaN,NaN,NaN,NaN,NaN,0.492038,50.796207,2025_01_ARI_NO,2025090705,ARI,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",7.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",4.0,00-0035258;00-0034780;00-0039860;00-0034760;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0039860;00-0034760;00-0038995;00...,11.0,11.0,NaN,NaN,True,,ZONE_COVERAGE,COVER_6,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Kool-Aid McKinstry;Nathan Shepher...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,72;63;74;1;6;73;70;85;87;17;18,27;4;93;90;23;20;56;92;94;96;21
5,135.0,2025_01_ARI_NO,2025090705,NO,ARI,REG,1,ARI,away,NO,ARI,75.0,2025-09-07,777.0,1677.0,3477.0,Half1,0.0,1.0,0.0,1.0,2.0,0,12:57,ARI 25,21.0,2.0,(12:57) (Shotgun) 6-J.Conner left end to ARI 2...,run,-2.0,1.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,left,end,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003502,0.169071,0.002966,0.317244,0.176426,0.004497,0.326294,0.0,0.0,0.088479,-1.284150,2.203922,-2.203922,1.474202,-1.474202,0.37702,-0.37702,NaN,NaN,0.000000,0.000000,0.359325,-0.359325,-1.676665,1.676665,0.359325,-0.359325,-1.676665,1.676665,0.404215,0.595785,0.595785,0.404215,-0.024458,-0.053802,0.053802,0.620243,0.379757,0.659076,0.340924,0.038463,-0.038463,0.015689,-0.015689,NaN,NaN,0.0,0.000000,0.0,0.0,-0.034995,0.034995,0.0,0.0,-0.034995,0.034995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0033553,J.Conner,-2.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,00-0039860,K.McKinstry,None,None,None,None,None,None,None,None,None,None,None,None,NO,None,00-0039860,None,K.McKinstry,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,2.0,0.0,Punt,135.0,"9/7/25, 13:02:38",2025-09-07T17:05:25.293Z,Caesars Superdome,"Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph",f591a18c-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T17:05:29.833Z,None,1.0,Punt,2025-09-07T17:02:38.787Z,5.0,3:33,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:27,ARI 22,ARI 24,40.0,188.0,20,13,Home,-7,33,-6.0,44.5,0,dome,sportturf,NaN,NaN,Kellen Moore,Jonathan Gannon,NOR00,Mercedes-Benz Superdome,0.0,0.0,None,NaN,J.Conner,6.0,None,NaN,0.0,1.0,0.0,0.0,1.0,None,00-0033553,None,J.Conner,6.0,00-0033553,J.Conner,00-0033553,J.Conner,00-0033553,0.0,0.0,-1.284150,NaN,NaN,NaN,NaN,NaN,0.716846,-71.684570,2025_01_ARI_NO,2025090705,ARI,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",6.0,"3 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 2 OLB, 1 SS",0.0,00-0035258;00-0034780;00-0038121;00-0039860;00...,00-0035258;00-0034495;00-0039808;00-0035228;00...,00-0034780;00-0038121;00-0039860;00-0034760;00...,11.0,11.0,NaN,NaN,False,,,None,Hjalte Froholdt;Evan Brown;Isaiah Adams;Kyler ...,Isaac Yiadom;Alontae Taylor;Kool-Aid McKinstry...,C;G;G;QB;RB;T;T;TE;WR;WR;WR,CB;CB;CB;DT;DT;FS;ILB;MLB;OLB;OLB;SS,72;63;74;1;6;73;70;85;17;14;18,27;1;4;93;90;23;20;56;94;96;21

In [4]:
# =========================================================
# FOURTH CELL — CREATE DOWN & DISTANCE BUCKETS
# =========================================================

def get_bucket(row):
    down = int(row["down"])
    y = row["ydstogo"]

    if down == 1:
        if y == 10:
            return "1st & 10"
        else:
            return None

    if down == 2:
        if 1 <= y <= 2:
            return "2nd & 1-2"
        elif 3 <= y <= 6:
            return "2nd & 3-6"
        elif y >= 7:
            return "2nd & 7+"

    if down == 3:
        if 1 <= y <= 2:
            return "3rd & 1-2"
        elif 3 <= y <= 5:
            return "3rd & 3-5"
        elif 6 <= y <= 9:
            return "3rd & 6-9"
        elif y >= 10:
            return "3rd & 10+"

    if down == 4:
        if 1 <= y <= 2:
            return "4th & 1-2"
        elif y >= 3:
            return "4th & 3+"

    return None

clean["bucket"] = clean.apply(get_bucket, axis=1)

# remove anything not in a bucket
clean = clean[clean["bucket"].notna()]

print(clean["bucket"].value_counts())

bucket
1st & 10     11106
2nd & 7+      5392
2nd & 3-6     2538
3rd & 10+     1514
3rd & 6-9     1497
3rd & 3-5     1313
3rd & 1-2     1068
2nd & 1-2      805
4th & 1-2      320
4th & 3+       309
Name: count, dtype: int64

In [16]:
def build_table(team):
    team_df = clean[clean["posteam"] == team]

    rows = []

    order = [
        "1st & 10",
        "2nd & 1-2",
        "2nd & 3-6",
        "2nd & 7+",
        "3rd & 1-2",
        "3rd & 3-5",
        "3rd & 6-9",
        "3rd & 10+",
        "4th & 1-2",
        "4th & 3+"
    ]

    for bucket in order:
        g = team_df[team_df["bucket"] == bucket]

        runs = g[g["play_type"] == "run"]
        passes = g[g["play_type"] == "pass"]

        total = len(g)

        run_ypp = f"{runs['yards_gained'].mean():.1f}" if len(runs) > 0 else "-"
        pass_ypp = f"{passes['yards_gained'].mean():.1f}" if len(passes) > 0 else "-"
        all_ypp = f"{g['yards_gained'].mean():.1f}" if total > 0 else "-"

        rows.append({
            "Down & Distance": bucket,
            "Run %": f"{round(100 * len(runs) / total)}%" if total > 0 else "0%",
            "Run Plays": len(runs),
            "Run Yds/Play": run_ypp,
            "Pass Plays": len(passes),
            "Pass Yds/Play": pass_ypp,
            "All Plays": total,
            "All Yds/Play": all_ypp
        })

    table = pd.DataFrame(rows)

    # TOTAL ROW
    total_df = team_df
    runs = total_df[total_df["play_type"] == "run"]
    passes = total_df[total_df["play_type"] == "pass"]

    total_row = pd.DataFrame([{
        "Down & Distance": "Total",
        "Run %": f"{round(100 * len(runs) / len(total_df))}%",
        "Run Plays": len(runs),
        "Run Yds/Play": f"{runs['yards_gained'].mean():.1f}",
        "Pass Plays": len(passes),
        "Pass Yds/Play": f"{passes['yards_gained'].mean():.1f}",
        "All Plays": len(total_df),
        "All Yds/Play": f"{total_df['yards_gained'].mean():.1f}"
    }])

    table = pd.concat([table, total_row], ignore_index=True)

    return table

In [17]:
commanders = build_table("WAS")
eagles = build_table("PHI")
colts = build_table("IND")

In [18]:
print(commanders)
print(eagles)
print(colts)

   Down & Distance Run %  Run Plays Run Yds/Play  Pass Plays Pass Yds/Play  All Plays All Yds/Play
0         1st & 10   60%        206          4.9         135           6.7        341          5.6
1        2nd & 1-2   79%         23          4.3           6           7.2         29          4.9
2        2nd & 3-6   54%         45          5.8          38          10.0         83          7.7
3         2nd & 7+   30%         45          6.0         104           7.2        149          6.8
4        3rd & 1-2   77%         20          3.0           6           6.2         26          3.7
5        3rd & 3-5   17%          6          3.2          29           3.4         35          3.3
6        3rd & 6-9   10%          4         14.2          36           5.4         40          6.3
7        3rd & 10+   11%          5         13.4          39           6.6         44          7.4
8        4th & 1-2   25%          2          1.5           6           6.3          8          5.1
9         4th & 3+   11%          1          7.0           8           7.6          9          7.6
10           Total   47%        357          5.2         407           6.8        764          6.0
   Down & Distance Run %  Run Plays Run Yds/Play  Pass Plays Pass Yds/Play  All Plays All Yds/Play
0         1st & 10   55%        183          4.4         147           6.9        330          5.5
1        2nd & 1-2   63%         19          4.6          11           9.7         30          6.5
2        2nd & 3-6   46%         36          6.2          43           8.6         79          7.5
3         2nd & 7+   37%         60          5.3         104           4.2        164          4.6
4        3rd & 1-2   68%         13          5.2           6           4.2         19          4.9
5        3rd & 3-5   19%          7          4.7          29           5.2         36          5.1
6        3rd & 6-9   16%          9          5.4          47           6.2         56          6.1
7        3rd & 10+   24%         14          6.3          45           9.5         59          8.7
8        4th & 1-2  100%          3          6.3           0             -          3          6.3
9         4th & 3+   22%          2        -14.5           7           6.6          9          1.9
10           Total   44%        346          4.8         439           6.5        785          5.8
   Down & Distance Run %  Run Plays Run Yds/Play  Pass Plays Pass Yds/Play  All Plays All Yds/Play
0         1st & 10   47%        164          5.2         184           8.1        348          6.7
1        2nd & 1-2   67%         22          7.4          11           5.2         33          6.6
2        2nd & 3-6   62%         41          5.7          25           6.2         66          5.9
3         2nd & 7+   20%         32          4.5         125           5.9        157          5.6
4        3rd & 1-2   53%         16          5.6          14           9.4         30          7.4
5        3rd & 3-5   21%          9          6.1          34           6.8         43          6.7
6        3rd & 6-9   11%          4          5.2          33           7.9         37          7.6
7        3rd & 10+   23%          9          7.0          30          10.9         39         10.0
8        4th & 1-2   64%          9          2.1           5           3.2         14          2.5
9         4th & 3+    0%          0            -           4           8.0          4          8.0
10           Total   40%        306          5.3         465           7.4        771          6.6

In [28]:
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

def simple_table(df, subtitle, title_color, table_color, pdf):
    fig, ax = plt.subplots(figsize=(12, 7))
    ax.axis("off")

    # --- TITLE BAR (TEAM PRIMARY COLOR) ---
    ax.add_patch(
        Rectangle(
            (0, 0.88),
            1,
            0.12,
            transform=ax.transAxes,
            color=title_color
        )
    )

    ax.text(
        0.5, 0.94,
        "Offensive Run / Pass Summary",
        transform=ax.transAxes,
        ha="center",
        va="center",
        fontsize=16,
        color="white",
        weight="bold"
    )

    ax.text(
        0.5, 0.90,
        subtitle,
        transform=ax.transAxes,
        ha="center",
        va="center",
        fontsize=11,
        color="white",
        weight="bold"
    )

    # --- TABLE ---
    table = ax.table(
        cellText=df.values,
        colLabels=df.columns,
        cellLoc="center",
        bbox=[0, 0.05, 1, 0.83]
    )

    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.1, 1.5)

    # style cells
    for (r, c), cell in table.get_celld().items():
        cell.set_edgecolor("black")
        cell.set_linewidth(1.0)

        # header
        if r == 0:
            cell.set_facecolor(table_color)
            cell.set_text_props(color="white", weight="bold")

        # total row
        if r == len(df):
            cell.set_facecolor(table_color)
            cell.set_text_props(color="white", weight="bold")

    # --- FOOTNOTE ---
    ax.text(
        0.5, 0.03,
        "Excludes red zone, backed up field position, penalties, and non-standard situations",
        transform=ax.transAxes,
        ha="center",
        va="center",
        fontsize=9,
        color="black"
    )

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


# --- EXPORT PDF ---
with PdfPages("CommandersQuantAssessment_Part2.pdf") as pdf:
    simple_table(
        commanders,
        "Washington Commanders - 2025 Regular Season",
        title_color="#5A1414",   # burgundy
        table_color="#FFB612",   # GOLD
        pdf=pdf
)

    simple_table(
        eagles,
        "Philadelphia Eagles - 2025 Regular Season",
        title_color="#004C54",   # green
        table_color="#6C7A7D",   # silver
        pdf=pdf
    )

    simple_table(
        colts,
        "Indianapolis Colts - 2025 Regular Season",
        title_color="#002C5F",   # blue
        table_color="#5F6A6A",   # grey
        pdf=pdf
    )